/*
  Standard action types that are used in reducers and dispatcher calls
 */
export const UPDATE_GRAPH_DATA = 'UPDATE_GRAPH_DATA';
export const UPDATE_PIECHART_DATA = 'UPDATE_PIECHART_DATA';
export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
export const UPDATE_LAST_CHANGED = 'UPDATE_LAST_CHANGED';
export const UPDATE_AUTHENTICATION = 'UPDATE_AUTHENTICATION';
export const UPDATE_DETAIL_DATA = 'UPDATE_DETAIL_DATA';
export const CHANGE_TAB = 'CHANGE_TAB';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';

// New Reducers
export const UPDATE_HISTORICAL_DATA = 'UPDATE_HISTORICAL_DATA';
export const USER_SETTINGS_UPDATE_NAME = 'USER_SETTINGS_UPDATE_NAME';
export const USER_SETTINGS_UPDATE_ZIPCODE = 'USER_SETTINGS_UPDATE_ZIPCODE';
export const USER_SETTINGS_TOGGLE_MAIL = 'USER_SETTINGS_TOGGLE_MAIL';
export const USER_SETTINGS_UPDATE_MAIL = 'USER_SETTINGS_UPDATE_MAIL';
export const USER_SETTINGS_UPDATE_EMAIL = 'USER_SETTINGS_UPDATE_EMAIL';
export const USER_SETTINGS_UPDATE_ERR_EMAIL = 'USER_SETTINGS_UPDATE_ERR_EMAIL';
export const DASHBOARD_RESET_MODAL = 'DASHBOARD_RESET_MODAL';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';
export const TOGGLE_SHOW_SEARCH_OPTION = 'TOGGLE_SHOW_SEARCH_OPTION';
export const AMAZON_RESULTS_SELECTION = 'AMAZON_RESULTS_SELECTION';
export const RESET_SHIP_QUANTITY = 'RESET_SHIP_QUANTITY';
export const UPDATE_SHIP_QUANTITY = 'UPDATE_SHIP_QUANTITY';
export const UPDATE_MODAL_SIZE = 'UPDATE_MODAL_SIZE';
export const TOGGLE_SHOW_MODAL = 'TOGGLE_SHOW_MODAL';
export const TOGGLE_SHIP_MODAL = 'TOGGLE_SHIP_MODAL';
export const TOGGLE_DELETE_MODAL = 'TOGGLE_DELETE_MODAL';
export const HIDE_SEARCH = 'HIDE_SEARCH';
export const UPDATE_ERR_SHIP_QUANTITY = 'UPDATE_ERR_SHIP_QUANTITY';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const FORM_SMART_ADD = 'FORM_SMART_ADD';
export const UPDATE_FORM_ERR_ASIN = 'UPDATE_FORM_ERR_ASIN';
export const UPDATE_FORM_ERR_QUANTITY = 'UPDATE_FORM_ERR_QUANTITY';
export const UPDATE_FORM_ERR_SELLER_SKU = 'UPDATE_FORM_ERR_SELLER_SKU';
export const UPDATE_FORM_ERR_PURCHASE_PRICE = 'UPDATE_FORM_ERR_PURCHASE_PRICE';
export const UPDATE_FORM_ERR_PURCHASE_DATE = 'UPDATE_FORM_ERR_PURCHASE_DATE';
export const UPDATE_FORM_PURCHASE_DATE = 'UPDATE_FORM_PURCHASE_DATE';
export const UPDATE_FORM_QUANTITY = 'UPDATE_FORM_QUANTITY';
export const UPDATE_FORM_PURCHASE_PRICE = 'UPDATE_FORM_PURCHASE_PRICE';
export const UPDATE_FORM_SELLER_SKU = 'UPDATE_FORM_SELLER_SKU';
export const UPDATE_FORM_ASIN = 'UPDATE_FORM_ASIN';
export const UPDATE_LAST_CHANGED_DETAIL_ID = 'UPDATE_LAST_CHANGED_DETAIL_ID';
