/*
  Standard action types that are used in reducers and dispatcher calls
 */
export const UPDATE_GRAPH_DATA = 'UPDATE_GRAPH_DATA';
export const UPDATE_PIECHART_DATA = 'UPDATE_PIECHART_DATA';
export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
export const UPDATE_LAST_CHANGED = 'UPDATE_LAST_CHANGED';
export const UPDATE_AUTHENTICATION = 'UPDATE_AUTHENTICATION';
export const UPDATE_DETAIL_DATA = 'UPDATE_DETAIL_DATA';
export const CHANGE_TAB = 'CHANGE_TAB';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';



export const USER_SETTINGS_UPDATE_NAME = 'USER_SETTINGS_UPDATE_NAME';
export const USER_SETTINGS_UPDATE_ZIPCODE = 'USER_SETTINGS_UPDATE_ZIPCODE';
export const USER_SETTINGS_TOGGLE_MAIL = 'USER_SETTINGS_TOGGLE_MAIL';
export const USER_SETTINGS_UPDATE_MAIL = 'USER_SETTINGS_UPDATE_MAIL';
export const USER_SETTINGS_UPDATE_EMAIL = 'USER_SETTINGS_UPDATE_EMAIL';
export const USER_SETTINGS_UPDATE_ERR_EMAIL = 'USER_SETTINGS_UPDATE_ERR_EMAIL';






